# Generated by Django 6.0.5 on 2026-06-28 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Advogado')),
                ('oab', models.CharField(max_length=20, unique=True, verbose_name='Inscrição OAB')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Cadastro Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Cadastro Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Fórum')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fórum',
                'verbose_name_plural': 'Fóruns',
            },
        ),
        migrations.CreateModel(
            name='Juiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Juiz')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Cadastro Ativo')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.forum', verbose_name='Fórum Vinculado')),
            ],
            options={
                'verbose_name': 'Juiz',
                'verbose_name_plural': 'Juízes',
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Login no Sistema'), ('BUSCA', 'Realizou Pesquisa'), ('VISUALIZACAO', 'Visualizou Processo')], max_length=20, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição da Atividade')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Número do Processo')),
                ('status', models.CharField(choices=[('ativo', 'Em Andamento / Ativo'), ('encerrado', 'Encerrado / Julgado'), ('substabelecido', 'Substabelecido (Outro Escritório)'), ('desistencia', 'Desistência pelo Cliente'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status do Processo')),
                ('resumo_sentenca', models.TextField(blank=True, null=True, verbose_name='Resumo da Causa / Sentença')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.advogado', verbose_name='Advogado Responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.cliente', verbose_name='Cliente')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='processos.forum', verbose_name='Fórum')),
                ('juiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.juiz', verbose_name='Juiz Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(verbose_name='Histórico / Movimentação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='processos.processo')),
            ],
        ),
        migrations.CreateModel(
            name='AndamentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição do Andamento')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Andamento do Processo',
                'verbose_name_plural': 'Andamentos do Processo',
                'ordering': ['-data'],
            },
        ),
    ]
