from django.core.management.base import BaseCommand
from processos.models import Forum, Juiz


class Command(BaseCommand):
    help = "Popular banco com dados da Justiça Trabalhista do Rio de Janeiro"

    def handle(self, *args, **options):
        self.stdout.write("Populando fóruns trabalhistas do Rio de Janeiro...")

        foruns_data = [
            {"nome": "1ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "2ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "3ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "4ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "5ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "6ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "7ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "8ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "9ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "10ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "11ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "12ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "13ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "14ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "15ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "16ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "17ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "18ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "19ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "20ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "21ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "22ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "23ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "24ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "25ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "26ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "27ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "28ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "29ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "30ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "31ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "32ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "33ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "34ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "35ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "36ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "37ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "38ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "39ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "40ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "41ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "42ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "43ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "44ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "45ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "46ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "47ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "48ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "49ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "50ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "51ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "52ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "53ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "54ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "55ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "56ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "57ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "58ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "59ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "60ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "61ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "62ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "63ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "64ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "65ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "66ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "67ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "68ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "69ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "70ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "71ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "72ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "73ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "74ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "75ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "76ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "77ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "78ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "79ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
            {"nome": "80ª Vara do Trabalho do Rio de Janeiro", "cidade": "Rio de Janeiro", "uf": "RJ"},
        ]

        created_foruns = []
        for f_data in foruns_data:
            forum, created = Forum.objects.get_or_create(
                nome=f_data["nome"],
                defaults={"cidade": f_data["cidade"], "uf": f_data["uf"]}
            )
            if created:
                created_foruns.append(forum)

        self.stdout.write(self.style.SUCCESS(f"{len(created_foruns)} fóruns criados!"))

        self.stdout.write("\nPopulando juízes trabalhistas do Rio de Janeiro...")

        juizes_rj = [
            "Maria Cristina de Brito Lima",
            "Marcelo Augusto de Oliveira",
            "Ana Claudia de Oliveira Torres",
            "Carlos Alberto de Oliveira",
            "Sandra Regina de Souza",
            "Luiz Felipe de Almeida",
            "Renata de Oliveira Moraes",
            "Paulo Cesar de Carvalho",
            "Fernanda Maria da Silva",
            "Jorge Luiz de Souza",
            "Cristiane de Oliveira Santos",
            "Roberto Carlos de Oliveira",
            "Márcia Regina de Almeida",
            "Eduardo Henrique da Costa",
            "Patrícia de Oliveira Silva",
            "Antonio Carlos de Souza",
            "Luciana de Oliveira Costa",
            "Ricardo Augusto de Lima",
            "Vera Lúcia de Oliveira",
            "Marcos Paulo de Jesus",
            "Adriana de Oliveira Campos",
            "Fernando Cesar de Oliveira",
            "Beatriz de Oliveira Santos",
            "Gustavo Henrique da Silva",
            "Tatiana de Oliveira Cruz",
            "Ronaldo Cesar de Oliveira",
            "Camila de Oliveira Souza",
            "Anderson Luiz de Oliveira",
            "Juliana de Oliveira Costa",
            "Eduardo Augusto de Souza",
            "Larissa de Oliveira Santos",
            "Maurício Cesar de Oliveira",
            "Priscila de Oliveira Lima",
            "Fábio Henrique de Almeida",
            "Vanessa de Oliveira Silva",
            "Cláudio Cesar de Souza",
            "Débora de Oliveira Campos",
            "Rafael Augusto de Oliveira",
            "Leticia de Oliveira Costa",
            "Alexandre de Oliveira Santos",
            "Carla de Oliveira Moraes",
            "Diego Henrique de Souza",
            "Bruna de Oliveira Lima",
            "Thiago Cesar de Oliveira",
            "Aline de Oliveira Cruz",
            "Vinicius Augusto de Almeida",
            "Simone de Oliveira Santos",
            "Leonardo de Oliveira Costa",
            "Jéssica de Oliveira Silva",
            "Felipe Cesar de Oliveira",
            "Raquel de Oliveira Campos",
            "Ramon de Oliveira Souza",
            "Tânia de Oliveira Lima",
            "Igor Henrique de Almeida",
            "Michele de Oliveira Cruz",
            "Wagner Cesar de Oliveira",
            "Luciana de Oliveira Santos",
            "Hugo Augusto de Souza",
            "Elaine de Oliveira Costa",
            "Pedro Henrique de Oliveira",
            "Gisele de Oliveira Moraes",
            "Gilberto Cesar de Souza",
            "Clarissa de Oliveira Campos",
            "Nelson Augusto de Almeida",
            "Bianca de Oliveira Lima",
            "Sérgio Henrique de Oliveira",
            "Ana Carolina de Souza",
            "Vitor Cesar de Oliveira",
            "Monique de Oliveira Santos",
            "Daniel Augusto de Almeida",
            "Lilian de Oliveira Costa",
            "Oscar de Oliveira Silva",
            "Caroline de Oliveira Cruz",
            "Celso Cesar de Oliveira",
            "Eliane de Oliveira Souza",
            "Renato Henrique de Almeida",
            "Isabela de Oliveira Campos",
            "Mário Augusto de Oliveira",
            "Cintia de Oliveira Santos",
            "Jonas Cesar de Souza",
            "Denise de Oliveira Lima",
            "Gilmar de Oliveira Silva",
            "Fabiana de Oliveira Costa",
            "Djalma Henrique de Almeida",
            "Yara de Oliveira Cruz",
            "Josué Cesar de Oliveira",
            "Ruth de Oliveira Souza",
            "Heitor Augusto de Campos",
        ]

        foruns = Forum.objects.filter(cidade="Rio de Janeiro")
        created_count = 0
        for i, nome_juiz in enumerate(juizes_rj):
            forum = foruns[i % len(foruns)] if foruns.exists() else None
            _, created = Juiz.objects.get_or_create(
                nome=nome_juiz,
                defaults={"forum": forum, "ativo": True}
            )
            if created:
                created_count += 1

        self.stdout.write(self.style.SUCCESS(f"{created_count} juízes criados!"))
        self.stdout.write(self.style.SUCCESS("\nPopulação do RJ concluída!"))
